### PR TITLE
Fixed dynamic coordinate refresh for ELAN v3 touchpads

### LINKED ISSUE #1192: Trackpad Elan v3 the pointer moves not correctly.
The trackpad Elan v3 works ~~only as a mouse.~~
Doubleclick works.
Trackpad keys work.
~~Gestures don't work.~~
~~Trackpad preferens panel don't work.~~

What logs are required from me?
CC @BAndysc и @hieplpvip

### PR DESCRIPTION
**Pull request by vit9696**
closes acidanthera/bugtracker#1192

### CODE REVIEW

**Review by hieplpvip — APPROVED** [review]

**Comment by BAndysc** [comment]
Nice catch 👍

**Review by BAndysc — APPROVED** [review]
Nice catch 👍

**Comment by hieplpvip** [comment]
@usr-sse2 Latest commit doesn't update `info.x_max`, `info.y_max`, etc.

**Comment by vit9696** [comment]
The attempt to add support for padding fields failed, so we decided to merge the initial fix to master, and then continue investigating better gesture compatibility as time permits. I am closing this PR but leaving the branch alive for later debugging as needed.

**Pull request closed without merging**
