### PR TITLE
Change minimum macOS to 10.10

### PR DESCRIPTION
**Pull request by Lost-Entrepreneur439**
VoodooPS2 fully works on Yosemite without any modifications, no idea why the minimum is set to El Capitan.

### CODE REVIEW

**Comment by vit9696** [comment]
VoodooInput also targets 10.11 min, are you sure that both work fine on 10.10? If so, you will need to lower the requirements for VoodooInput as well.

CC @kprinssu, @1Revenger1, @usr-sse2

**Comment by Lost-Entrepreneur439** [comment]
> VoodooInput also targets 10.11 min, are you sure that both work fine on 10.10? If so, you will need to lower the requirements for VoodooInput as well.
> 
> CC @kprinssu, @1Revenger1, @usr-sse2

VoodooInput works fine on 10.10 too, it even has comments that mention 10.10. Opening a PR there as well.

**Comment by kprinssu** [comment]
Please link the upstream changes and PR to VoodooInput here as well.

**Comment by Lost-Entrepreneur439** [comment]
https://github.com/acidanthera/VoodooInput/pull/27

**Pull request merged**
